In [3]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [3]:
a = tf.range(2*2*2*5)

In [4]:
a

<tf.Tensor: shape=(40,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39], dtype=int32)>

In [10]:
a = tf.reshape(a,(2,2,2,5))

In [11]:
a[1,1,:,:]

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]], dtype=int32)>

In [12]:
a = tf.reshape(a,(2*2*2,5))

In [13]:
a

<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]], dtype=int32)>

In [14]:
grid_size= 16
num_anchors = 4

x = tf.range(grid_size, dtype=tf.float32)
y = tf.range(grid_size, dtype=tf.float32)

#x_offset = 
#x_offset, y_offset = tf.meshgrid(x, y)
#x_offset = tf.reshape(x_offset, (-1, 1))
#y_offset = tf.reshape(y_offset, (-1, 1))
x_offset=x_offset[:,:,tf.newaxis]
y_offset=y_offset[:,:,tf.newaxis]
x_y_offset = tf.concat([x_offset, y_offset], axis=2)
#x_y_offset = tf.tile(x_y_offset, [1, num_anchors])
#x_y_offset = tf.reshape(x_y_offset, [1, -1, 2])     

NameError: name 'x_offset' is not defined

In [15]:
x = tf.reshape(x,(2,2,4))
print(x[0,0,:])

tf.Tensor([0. 1. 2. 3.], shape=(4,), dtype=float32)


In [16]:
x = tf.reshape(x,(2,2,2,2))
print(x[0,0,:,:])

tf.Tensor(
[[0. 1.]
 [2. 3.]], shape=(2, 2), dtype=float32)


In [17]:
x_offset[:,:,0]

NameError: name 'x_offset' is not defined

In [18]:
print(x_y_offset.shape)

NameError: name 'x_y_offset' is not defined

In [19]:
x_y_offset = tf.reshape(x_y_offset,[1,-1,1])

NameError: name 'x_y_offset' is not defined

In [20]:
x_y_offset.shape

NameError: name 'x_y_offset' is not defined

In [21]:
x_y_offset

NameError: name 'x_y_offset' is not defined

In [3]:
grid_size=3

x = tf.range(grid_size, dtype=tf.float32)
y = tf.range(grid_size, dtype=tf.float32)
x_offset, y_offset = tf.meshgrid(x, y)

In [97]:
416//13

32

In [98]:
200/32

6.25

In [99]:
32*5

160

In [4]:
6*32

192

In [17]:
#para calcular el x


In [81]:
bbox =np.array([[0.2,0.3,0.6,0.8],[0.25,0.05,0.5,0.2]])
bbox = bbox -np.tile(bbox[:,:2],2)
#print(bbox)

In [85]:
bbox

array([[0.  , 0.  , 0.4 , 0.5 ],
       [0.  , 0.  , 0.25, 0.15]])

In [4]:
def get_iou_vector(A, B):
    # Numpy version
    
    batch_size = A.shape[0]
    metric = 0.0
    for batch in range(batch_size):
        t, p = A[batch], B[batch]
        true = np.sum(t)
        pred = np.sum(p)
        
        # deal with empty mask first
        if true == 0:
            metric += (pred == 0)
            continue
        
        # non empty mask case.  Union is never empty 
        # hence it is safe to divide by its number of pixels
        intersection = np.sum(t * p)
        union = true + pred - intersection
        iou = intersection / union
        
        # iou metrric is a stepwise approximation of the real iou over 0.5
        iou = np.floor(max(0, (iou - 0.45)*20)) / 10
        
        metric += iou
        
    # teake the average over all images in batch
    metric /= batch_size
    return metric

In [5]:
anchors =np.array([[0,0,10/416,14/416],[0,0,23/416,27/416],[0,0,37/416,58/416],[0,0,81/416,82/416]])
print(anchors)

[[0.         0.         0.02403846 0.03365385]
 [0.         0.         0.05528846 0.06490385]
 [0.         0.         0.08894231 0.13942308]
 [0.         0.         0.19471154 0.19711538]]


In [6]:
get_iou_matrix_tf(bbox,anchors)

NameError: name 'get_iou_matrix_tf' is not defined

In [39]:
#de VOC format to YOLO forma
def sigmoid(x):
    return 1/(1 + np.exp(-x)) 

x_min,y_min,x_max,y_max = bbox

width = x_max-x_min
height = y_max-y_min
x_global =x_min + (x_max - x_min)/2
y_global =y_min + (y_max - y_min)/2

pixel_per_grid = 1/13
offset_grid_x = x_global//pixel_per_grid
offset_grid_y = y_global//pixel_per_grid


x_local =x_global%pixel_per_grid
y_local = y_global%pixel_per_grid

tx = np.log(x_local/(1-x_local))
ty = np.log(y_local/(1-y_local))




#
x_global = (offset_grid_x * pixel_per_grid) + sigmoid(tx)
y_global = (offset_grid_y * pixel_per_grid) + sigmoid(ty)

print(x_global,y_global,width,height)
print(tx,ty)

0.4 0.5 0.39999999999999997 0.6000000000000001
-4.1588830833596715 -3.2188758248682015


In [24]:
(0.2*416)

83.2

In [3]:
import numpy as np
import tensorflow as tf
#import matplotlib.pylot as plt

In [4]:
def get_iou_matrix_tf(box_arr1, box_arr2):
    
    box_arr1 = box_arr1 -tf.tile(box_arr1[:,:2],[1,2])
    #print(box_arr1)
    x11, y11, x12, y12 = tf.split(box_arr1, 4, axis=1)
    x21, y21, x22, y22 = tf.split(box_arr2, 4, axis=1)
    xA = tf.maximum(x11, tf.transpose(x21))
    yA = tf.maximum(y11, tf.transpose(y21))
    xB = tf.minimum(x12, tf.transpose(x22))
    yB = tf.minimum(y12, tf.transpose(y22))
    interArea = tf.maximum((xB - xA + 1e-9), 0) * tf.maximum((yB - yA + 1e-9), 0)
    boxAArea = (x12 - x11 + 1e-9) * (y12 - y11 + 1e-9)
    boxBArea = (x22 - x21 + 1e-9) * (y22 - y21 + 1e-9)
    iou = interArea / (boxAArea + tf.transpose(boxBArea) - interArea)
    return iou,tf.argmax(iou,axis=1)#[:,tf.newaxis]

In [15]:
def fill_yolo_output(boxes,grid_size,num_anchors,which_anchor_box,which_anchor_box_index):
    print(boxes.shape)
    noobj_mask = tf.ones((1,grid_size*grid_size*num_anchors))
    #print(noobj_mask.shape)
    
    x_min,y_min,x_max,y_max =tf.split(boxes,4,axis=1)

    #Transforma las coordenadas de (xmin,ymin,xmax,ymax) --> (xcenter,ycenter,width,height)
    width = x_max-x_min
    height = y_max-y_min
    x_global =x_min + (x_max - x_min)/2
    y_global =y_min + (y_max - y_min)/2
    
    
    x_min_anchor,y_min_anchor,x_max_anchor,y_max_anchor =tf.split(which_anchor_box,4,axis=1)
    
    width_anchor = x_max_anchor-x_min_anchor
    height_anchor = y_max_anchor-y_min_anchor
    x_global_anchor =x_min_anchor + (x_max_anchor - x_min_anchor)/2
    y_global_anchor =y_min_anchor + (y_max_anchor - y_min_anchor)/2   

    
    print("el x original",x_global)
    print("el y original",y_global)
    print("el w original",width)
    print("el h original",height)
    
    #porción de la imagen que hay en cada celda
    pixel_per_grid = 1/grid_size
    #print(pixel_per_grid)
    
    #Obtenemos la coordenada de la celda donde están los boundingboxes
    offset_grid_x = x_global//pixel_per_grid
    offset_grid_y = y_global//pixel_per_grid
    
    #Obtenemos el el centro locacon referencia  al celda encontrada previamente
    x_local =x_global%pixel_per_grid
    y_local = y_global%pixel_per_grid
    #print(x_local,y_local)
    
    #Valores tx e ty del groudtruth
    tx = tf.math.log(x_local + 1e-07/(1-x_local))
    ty = tf.math.log(y_local+1e-07/(1-y_local))
    tw = tf.math.log(tf.math.divide(width+1e-07,width_anchor))
    th = tf.math.log(tf.math.divide(height+1e-07,height_anchor))
    tobj = tf.ones((th.shape[0],1))
    tnoobj = tf.zeros((th.shape[0],1))
    #print("Lo que la red debe predecir",tx.numpy(),ty.numpy(),tw.numpy(),th.numpy())
    
    x_global = (offset_grid_x * pixel_per_grid) + tf.math.sigmoid(tx)
    y_global = (offset_grid_y * pixel_per_grid) + tf.math.sigmoid(ty)
    w = width_anchor*tf.math.exp(tw)
    h = height_anchor*tf.math.exp(th)
    
    print("obtnemos el x_real",x_global)
    print("obtenemos el y_real",y_global)
    print("obtenemos el w real",w)
    print("obtenemos el h real",h)
    
    
    print(which_anchor_box_index)
    residuo = tf.math.floormod(which_anchor_box_index,2)[:,tf.newaxis]
    coord = tf.cast(2*(offset_grid_y*grid_size + offset_grid_x),dtype=tf.int64)
    
    
    output_position = residuo+coord
    print(output_position.shape)
    
    tx_vector = tf.sparse.SparseTensor(indices=output_position, values=tx[:,0], dense_shape=[grid_size*grid_size*num_anchors])
    ty_vector = tf.sparse.SparseTensor(indices=output_position, values=ty[:,0], dense_shape=[grid_size*grid_size*num_anchors])
    tw_vector = tf.sparse.SparseTensor(indices=output_position, values=tw[:,0], dense_shape=[grid_size*grid_size*num_anchors])
    th_vector = tf.sparse.SparseTensor(indices=output_position, values=th[:,0], dense_shape=[grid_size*grid_size*num_anchors])
    obj_mask = tf.sparse.SparseTensor(indices=output_position, values=tobj[:,0], dense_shape=[grid_size*grid_size*num_anchors])
    noobj_mask = tf.sparse.SparseTensor(indices=output_position, values=tnoobj[:,0], dense_shape=[grid_size*grid_size*num_anchors])
    #obj_mask =tx_vector=ty_vector=tw_vector=th_vector = tf.zeros((1,grid_size*grid_size*num_anchors))
    
    tx_vector = tf.sparse.to_dense(tx_vector, default_value=0, validate_indices=True, name=None)
    ty_vector = tf.sparse.to_dense(ty_vector, default_value=0, validate_indices=True, name=None)
    tw_vector = tf.sparse.to_dense(tw_vector, default_value=0, validate_indices=True, name=None)
    th_vector = tf.sparse.to_dense(th_vector, default_value=0, validate_indices=True, name=None)
    obj_mask = tf.sparse.to_dense(obj_mask, default_value=0, validate_indices=True, name=None)
    noobj_mask = tf.sparse.to_dense(noobj_mask, default_value=1, validate_indices=True, name=None)
    
    ##print(tx_vector.to_dense)
    #print(tf.sparse.to_dense(tx_vector, default_value=0, validate_indices=True, name=None))
    
    #tx_vector=tx_vector[[3,2],]
    #tx_vector[output_position[:,0]] = tx
    

    print("coordenada de la salida:",output_position)
    
    return None
    
    
#Esta tomará todos los anchor boxes y encontrará el mejor, entonces en esa celda, se debe poner que hay objeto y que sus correspondientes valores de tx,ty,tw,th.
def build_targets(image_bboxes,anchor_boxes,num_real_boxes):
    
    #Obtenemos los boduing boxes que son reales
    image_bboxes = image_bboxes[:num_real_boxes,:]
    print("Bouding boxes de la imagen",image_bboxes)
    #Obteneos  la matriz de IoU , y el índice del anchor box que dió mejor resultado
    iou_matrix,which_anchor_box_index = get_iou_matrix_tf(image_bboxes,anchor_boxes)
    
    print(which_anchor_box_index)

    #Indices de los bouding boxes que irian en cada salida, index_best_ yolo nos dice que bouding boxes de la imagen van a la salida YOLO1,
    #porque su mejor IoU fue con los dos anchor boxes mas grandes
    index_best_yolo1 = tf.where(which_anchor_box_index>=2)[:,0]
    index_best_yolo2 = tf.where(which_anchor_box_index<2)[:,0]
    index_best_anchor_yolo1 = tf.gather(which_anchor_box_index,index_best_yolo1,axis=0)
    index_best_anchor_yolo2 = tf.gather(which_anchor_box_index,index_best_yolo2,axis=0)
    
    print(index_best_yolo1)
    print(index_best_anchor_yolo1)

    print(index_best_yolo2)
    print(index_best_anchor_yolo2)

    
    best_bboxes_yolo1 = tf.gather(image_bboxes,index_best_yolo1,axis =0)
    best_anchors_yolo1 = tf.gather(anchor_boxes,index_best_anchor_yolo1, axis =0) #LOs dos anchor boxes grandes corrsponden a YOLO
    best_bboxes_yolo2 = tf.gather(image_bboxes,index_best_yolo2,axis =0)
    best_anchors_yolo2 = tf.gather(anchor_boxes,index_best_anchor_yolo2, axis =0) #Los dos anchor boxes pequeños corresponden a YOLO2
    
    
    if len(best_anchors_yolo1) !=0:
        fill_yolo_output(best_bboxes_yolo1,13,2,best_anchors_yolo1,index_best_anchor_yolo1)
    if len(best_anchors_yolo2) != 0:
        fill_yolo_output(best_bboxes_yolo2,26,2,best_anchors_yolo2,index_best_anchor_yolo2)


    return iou_matrix

In [24]:
bbox =tf.constant(np.array([[0.2,0.3,0.25,0.35],[0.25,0.05,0.5,0.2],[0.1,0.3,0.6,0.7],[0,0,0,0]]),dtype=tf.float32)
anchors =tf.constant(np.array([[0,0,0.015,0.037],[0,0,0.043,0.104],[0,0,0.11,0.278],[0,0,0.351,0.66]]),dtype=tf.float32)

bbox=tf.constant([[[0.1,0.2,0.4,0.9],[0.5,0.05,0.8,0.25],[0.4,0.4,0.8,0.8],[0,0,0,0]],[[0.2,0.3,0.6,0.8],[0.25,0.05,0.5,0.2],[0,0,0,0],[0,0,0,0]]],dtype=tf.float32)
print(bbox.shape)
build_targets(bbox,anchors,3)

(2, 4, 4)
Bouding boxes de la imagen tf.Tensor(
[[[0.1  0.2  0.4  0.9 ]
  [0.5  0.05 0.8  0.25]
  [0.4  0.4  0.8  0.8 ]
  [0.   0.   0.   0.  ]]

 [[0.2  0.3  0.6  0.8 ]
  [0.25 0.05 0.5  0.2 ]
  [0.   0.   0.   0.  ]
  [0.   0.   0.   0.  ]]], shape=(2, 4, 4), dtype=float32)


InvalidArgumentError: Expected multiples argument to be a vector of length 3 but got length 2 [Op:Tile]

In [22]:
bbox =np.array([[[0.1,0.2,0.4,0.9],[0.5,0.05,0.8,0.25],[0.4,0.4,0.8,0.8],[0,0,0,0]],[[0.2,0.3,0.6,0.8],[0.25,0.05,0.5,0.2],[0,0,0,0],[0,0,0,0]]])
x_min,y_min,x_max,y_max =tf.split(bbox,4,axis=1)

In [9]:
x_min

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[0.2 ],
       [0.25],
       [0.  ],
       [0.  ]])>