In [1]:
root_path = "/tf/home/sergio/Tesis"

In [2]:
import os
os.getcwd()

'/tf/home/sergio/Tesis/TinyYOLOv3-Pedestrian-Detection/Deployment'

In [3]:
import sys
sys.path.append(root_path+"/TinyYOLOv3-Pedestrian-Detection")
from YOLOblocks import TinyYOLOv3,BasicBlock,PredictionLayer#,YOLOLossBasicBlock

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import tensorflow as tf

from skimage.io import imread,imshow
from skimage.transform import resize
import time
import os

from pycocotools.coco import COCO

In [4]:
tf.__version__

'2.3.0'

In [5]:
#anchors =[[0.02078,0.049],[0.0426,0.128],[0.08523,0.19356],[0.1506,0.4163],[0.27835,0.58651],[0.5632,0.78614]]
anchors =[[0.026,0.062],[0.067,0.183],[0.128,0.323],[0.343,0.650]]

model = TinyYOLOv3(1,anchor_boxes=anchors,train=False,mode = "finetuning",obj_threshold=0.5)
model.build(batch_input_shape=(None,416,416,3))    
#model.load_weights(root_path+'/weights_saved/pesos_finetuning_5521_100_120_epoch_nadam_0dot00001_mse_exp_mse_3anchors')
model.load_weights(root_path+'/weights_saved/pesos_160_to_180_epochs_nadam_2_1_4_1_0dot0001_el_bueno')

In [6]:
file = tf.keras.utils.get_file(
    "persons.jpg",
    "https://www.saltwire.com/media/photologue/photos/cache/STJ-A01-28102019-RawlinsCrossPedestrians3_large.jpg")

In [7]:
image = file
img_raw = tf.image.decode_image(open(image, 'rb').read(), channels=3)
img = tf.expand_dims(img_raw, 0)
_,height,width,_ =img.shape
img = tf.image.resize(img, (416, 416))/255

In [8]:
boxes = model(img).numpy()

In [9]:
boxes

array([[[0.10112898, 0.36600646, 0.1594445 , 0.5506562 ],
        [0.64883703, 0.32231718, 0.7569186 , 0.7880667 ],
        [0.717958  , 0.22804555, 0.8576906 , 0.82031035],
        [0.5110128 , 0.19391859, 0.63435197, 0.8700261 ],
        [0.25065345, 0.36825904, 0.38760978, 0.9359809 ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.   

In [10]:
output = boxes[0,np.where(boxes[0,:,3]>0),:]

In [11]:
output

array([[[0.10112898, 0.36600646, 0.1594445 , 0.5506562 ],
        [0.64883703, 0.32231718, 0.7569186 , 0.7880667 ],
        [0.717958  , 0.22804555, 0.8576906 , 0.82031035],
        [0.5110128 , 0.19391859, 0.63435197, 0.8700261 ],
        [0.25065345, 0.36825904, 0.38760978, 0.9359809 ]]], dtype=float32)

### Saving the model

In [12]:
# Save the entire model as a SavedModel.
!mkdir -p saved_model_segunda_version_dos_anchors
model.save('saved_model_segunda_version_dos_anchors/my_model') 

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: saved_model_segunda_version_dos_anchors/my_model/assets


### Test the saved model

In [13]:
new_model = tf.keras.models.load_model('saved_model_segunda_version_dos_anchors/my_model')
# Check its architecture
new_model.summary()

Model: "tiny_yol_ov3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
BasicBlock1 (BasicBlock)     multiple                  496       
_________________________________________________________________
BasicBlock2 (BasicBlock)     multiple                  4736      
_________________________________________________________________
BasicBlock3 (BasicBlock)     multiple                  18688     
_________________________________________________________________
BasicBlock4 (BasicBlock)     multiple                  74240     
_________________________________________________________________
BasicBlock5 (BasicBlock)     multiple                  295936    
_________________________________________________________________
BasicBlock6 (BasicBlock)     multiple                  1181696   
_________________________________________________________________
BasicBlock7 (BasicBlock)     multiple                 

In [14]:
file = tf.keras.utils.get_file(
    "persons.jpg",
    "https://www.saltwire.com/media/photologue/photos/cache/STJ-A01-28102019-RawlinsCrossPedestrians3_large.jpg")

In [15]:
image = file
img_raw = tf.image.decode_image(open(image, 'rb').read(), channels=3)
img = tf.expand_dims(img_raw, 0)
_,height,width,_ =img.shape
img = tf.image.resize(img, (416, 416))/255

In [16]:
ayuda= model(img)
print(ayuda)

tf.Tensor(
[[[0.10112898 0.36600646 0.1594445  0.5506562 ]
  [0.64883703 0.32231718 0.7569186  0.7880667 ]
  [0.717958   0.22804555 0.8576906  0.82031035]
  [0.5110128  0.19391859 0.63435197 0.8700261 ]
  [0.25065345 0.36825904 0.38760978 0.9359809 ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.  

In [17]:
ayuda2= new_model(img)
print(ayuda2)

tf.Tensor(
[[[0.101129   0.36600643 0.15944451 0.5506562 ]
  [0.64883703 0.32231712 0.7569186  0.78806674]
  [0.717958   0.22804555 0.8576906  0.8203105 ]
  [0.5110128  0.1939185  0.63435197 0.87002623]
  [0.25065345 0.368259   0.38760978 0.935981  ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.  

In [18]:
%timeit model(img)

7.98 ms ± 90.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%timeit new_model(img)

7.55 ms ± 816 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
%timeit model(img)

6.97 ms ± 41.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit new_model(img)

5.52 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
